### ISSUE TITLE
Contribute to upstream

### ISSUE THREAD

**Issue by hasufell** [heftig/rtkit#1]
I see arch is patching things downstream, which is suboptimal. Why are these patches not contributed upstream?

**Comment by ewirch** [comment]
Does "[upstream](http://git.0pointer.net/rtkit.git)" has an issue tracker? I didn't find any.

**Comment by bl33pbl0p** [comment]
I think this is pratcially the upstream now, nobody else really maintains it.

**Comment by heftig** [comment]
Yeah, this is a fork now.
