### ISSUE TITLE
xml-introspection.S causes rtkit-daemon to have an executable stack

### ISSUE THREAD

**Issue by mkszuba** [heftig/rtkit#15]
This has already been both reported and explained in the Arch Linux bug tracker (https://bugs.archlinux.org/task/65699) so let me just mention here, for completeness, that setting the stack markings by adding

`#if defined(__linux__) && defined(__ELF__)`
`.section .note.GNU-stack,"",%progbits`
`#endif`

at the beginining of _xml-introspection.S_ makes the problem go away without, as far as I can tell from using a thus modified version of rtkit under Gentoo, any drawbacks.

This solution comes straight from generic Gentoo instructions for dealing with the executable stack and I take no credit for it, which is why I am posting it in an issue rather than submitting a pull request.

**Comment by heftig** [comment]
The current master replaces the use of assembler with `xxd` to convert the file into C code. The resulting file will be distributed in the tarballs, so `xxd` is not necessary.

**Comment by mkszuba** [comment]
Gah, I really should look at the master branch and not just at 0.12 before doing anything here. This is why I initially omitted meson while making libsystemd optional, too... Anyway, that's handy - and come next release, no more patches in Gentoo ebuilds of rtkit!
